apiVersion: v1
kind: Service
metadata:
  name: crop-ui-service
  labels:
    app: crop-ui
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30501
      protocol: TCP
  selector:
    app: crop-ui