apiVersion: apps/v1
kind: Deployment
metadata:
  name: crop-backend-deployment
  labels:
    app: crop-backend
    type: backend
spec:
  template:
    metadata:
      name: crop-backend
      labels:
        app: crop-backend
        type: backend
    spec:
      containers:
      - name: crop-backend
        image: tombriggs/crop-backend
  replicas: 3
  selector:
    matchLabels:
      type: backend

