apiVersion: apps/v1
kind: Deployment
metadata:
  name: crop-backend-deployment
  labels:
    app: crop-backend
    type: backend
spec:
  selector:
      matchLabels:
        app: crop-backend
  template:
    metadata:
      name: crop-backend
      labels:
        app: crop-backend
        type: backend
    spec:
      containers:
        - name: crop-backend
          image: tombriggs/crop-backend
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
          readinessProbe:
            httpGet:
              path: /api/v1/crop
              port: 8080
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /api/v1/crop
              port: 8080
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
  replicas: 1
  

